development:
  adapter: async

test:
  adapter: test

production:
  # adapter: redis ～を 削除
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: furima_production
